version: '3'

services:
  backend: 
    build: ./
    container_name: nestjs_api
    environment:
      - PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
    networks:
      - api_network

  db:
    container_name: db_postgres
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - api_network

networks:
  api_network:
    driver: bridge